version: 2.1
orbs:
  slack: circleci/slack@4.8.3
jobs:
  build: 
    environment:
      IMAGE_NAME: fairhivelabs/landing-page
    machine : true
    steps:
      - checkout
      - run:
          name: docker build
          command: DOCKER_BUILDKIT=1 docker build -t $IMAGE_NAME:$CIRCLE_BRANCH --build-arg BUILDKIT_INLINE_CACHE=1 .
      - run:
          name: docker tag
          command: docker tag $IMAGE_NAME:$CIRCLE_BRANCH $IMAGE_NAME:${CIRCLE_SHA1:0:8}
      - run:
          name: docker login
          command: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run:
          name: docker push
          command: docker push $IMAGE_NAME:$CIRCLE_BRANCH
      - run:
          name: docker push $IMAGE_NAME:${CIRCLE_SHA1:0:8}
          command: docker push $IMAGE_NAME:${CIRCLE_SHA1:0:8}
      - slack/notify:
          event: fail
          mentions: '@_whyvrafvr'
          template: basic_fail_1
      - slack/notify:
          event: pass
          custom: |
            {
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "*Docker image build & pushed*"
                  }
                },
                {
                  "type": "divider"
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": ":whale: Run docker image"
                  }
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "*`docker run -p 3000:80 -d --rm --name landing-page $IMAGE_NAME:$CIRCLE_BRANCH`*"
                  }
                }
              ]
            }
workflows:
  version: 2
  commit:
    jobs:
      - build:
          context: slack-secrets
          filters:
            branches:
              ignore: main
