version: 2.1
orbs:
  slack: circleci/slack@4.8.3
jobs:
  build_master:
    environment:
      IMAGE_NAME: fairhivelabs/landing-page
    machine : true
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: docker build
          command: docker build -t $IMAGE_NAME .
      - run:
          name: docker tag
          command: docker tag $IMAGE_NAME $IMAGE_NAME:${CIRCLE_SHA1:0:8}
      - run:
          name: docker login
          command: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run:
          name: docker push $IMAGE_NAME:latest
          command: docker push $IMAGE_NAME:latest
      - run:
          name: docker push $IMAGE_NAME:${CIRCLE_SHA1:0:8}
          command: docker push $IMAGE_NAME:${CIRCLE_SHA1:0:8}
  build: # generic job for other branches
    environment:
      IMAGE_NAME: fairhivelabs/landing-page
    machine : true
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: docker build
          command: docker build -t $IMAGE_NAME:$CIRCLE_BRANCH -f $CIRCLE_BRANCH.Dockerfile --build-arg BUILDKIT_INLINE_CACHE=1 .
      - run:
          name: docker login
          command: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run:
          name: docker push
          command: docker push $IMAGE_NAME:$CIRCLE_BRANCH
workflows:
  version: 2
  commit:
    jobs:
      - build_master:
          filters:
            branches:
              only: main
      - build:
          filters:
            branches:
              only: actors
